-- MySQL Script generated by MySQL Workbench
-- Fri Jan 13 00:18:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persons` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `age` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Workers` (
  `id` INT NOT NULL,
  `person_id` INT NOT NULL,
  `position` VARCHAR(45) NULL,
  `salary` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Employees_Persons1_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_Employees_Persons1`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`Persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customers` (
  `id` INT NOT NULL,
  `person_id` INT NOT NULL,
  `budget` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Customers_Persons_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_Customers_Persons`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`Persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Buildings costs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Buildings costs` (
  `id` INT NOT NULL,
  `cost_per_square_meter` INT NULL,
  `permit_cost` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Buildings timelines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Buildings timelines` (
  `id` INT NOT NULL,
  `construction_time` INT NULL,
  `permit_process_time` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Buildings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Buildings` (
  `id` INT NOT NULL,
  `building_cost_id` INT NOT NULL,
  `building_timeline_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Buildings_Buildings costs1_idx` (`building_cost_id` ASC) VISIBLE,
  INDEX `fk_Buildings_Buildings timelines1_idx` (`building_timeline_id` ASC) VISIBLE,
  CONSTRAINT `fk_Buildings_Buildings costs1`
    FOREIGN KEY (`building_cost_id`)
    REFERENCES `mydb`.`Buildings costs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Buildings_Buildings timelines1`
    FOREIGN KEY (`building_timeline_id`)
    REFERENCES `mydb`.`Buildings timelines` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Constructions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Constructions` (
  `id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `building_id` INT NOT NULL,
  `construction_id` INT NOT NULL,
  `is_paid` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Orders_Customers1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_Orders_Buildings1_idx` (`building_id` ASC) VISIBLE,
  INDEX `fk_Orders_Constructions1_idx` (`construction_id` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`Customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Buildings1`
    FOREIGN KEY (`building_id`)
    REFERENCES `mydb`.`Buildings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Constructions1`
    FOREIGN KEY (`construction_id`)
    REFERENCES `mydb`.`Constructions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teams` (
  `id` INT NOT NULL,
  `worker_id` INT NOT NULL,
  `construction_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Teams_Workers1_idx` (`worker_id` ASC) VISIBLE,
  INDEX `fk_Teams_Constructions1_idx` (`construction_id` ASC) VISIBLE,
  CONSTRAINT `fk_Teams_Workers1`
    FOREIGN KEY (`worker_id`)
    REFERENCES `mydb`.`Workers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teams_Constructions1`
    FOREIGN KEY (`construction_id`)
    REFERENCES `mydb`.`Constructions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
